// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IXcmRouter$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IXcmRouter";
  readonly sourceName: "contracts/interfaces/IXcmRouter.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"bytes","name":"beneficiary","type":"bytes"},{"internalType":"uint32","name":"destParaId","type":"uint32"},{"internalType":"uint64","name":"weight","type":"uint64"}],"name":"transferAssets","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"bytes","name":"beneficiary","type":"bytes"},{"internalType":"uint32","name":"destParaId","type":"uint32"},{"internalType":"uint64","name":"weight","type":"uint64"},{"internalType":"bytes","name":"memo","type":"bytes"}],"name":"transferAssetsWithMemo","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IXcmRouter.sol";
  readonly buildInfoId: "solc-0_8_20-4450347bc3500c408bf7d63b23f6763560f88769";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IXcmRouter"]: IXcmRouter$Type;
    ["contracts/interfaces/IXcmRouter.sol:IXcmRouter"]: IXcmRouter$Type;
  }
}